service: trading-platform

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

functions:
  processMarketData:
    handler: src.handlers.market_data.process
    events:
      - schedule: rate(5 minutes)

  executeTradeStrategy:
    handler: src.handlers.trade.execute
    events:
      - http:
          path: trade
          method: post

  analyzePerformance:
    handler: src.handlers.analysis.perform
    events:
      - s3:
          bucket: trading-data-${self:provider.stage}
          event: s3:ObjectCreated:*

resources:
  Resources:
    TradingDataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: trading-data-${self:provider.stage}

    TradingDatabase:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: trading-table-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-python-requirements
  - serverless-step-functions

stepFunctions:
  stateMachines:
    tradingWorkflow:
      definition:
        StartAt: FetchMarketData
        States:
          FetchMarketData:
            Type: Task
            Resource: ${self:functions.processMarketData.arn}
            Next: ExecuteTradeStrategy
          ExecuteTradeStrategy:
            Type: Task
            Resource: ${self:functions.executeTradeStrategy.arn}
            Next: AnalyzePerformance
          AnalyzePerformance:
            Type: Task
            Resource: ${self:functions.analyzePerformance.arn}
            End: true